/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real float
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int h_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int h_f_alloc_mem(void);
int h_f_init_mem(int mem);
void h_f_free_mem(int mem);
int h_f_checkout(void);
void h_f_release(int mem);
void h_f_incref(void);
void h_f_decref(void);
casadi_int h_f_n_in(void);
casadi_int h_f_n_out(void);
casadi_real h_f_default_in(casadi_int i);
const char* h_f_name_in(casadi_int i);
const char* h_f_name_out(casadi_int i);
const casadi_int* h_f_sparsity_in(casadi_int i);
const casadi_int* h_f_sparsity_out(casadi_int i);
int h_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int h_f_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define h_f_SZ_ARG 1
#define h_f_SZ_RES 1
#define h_f_SZ_IW 0
#define h_f_SZ_W 3
#ifdef __cplusplus
} /* extern "C" */
#endif
